import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import SidebarDemo from "@/components/sidebar";
import { Navbar } from "@/components/navbar/navbar";
import { cn } from "@/lib/utils";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          poppins.variable
        )}
      >
        <SidebarProvider>
          <div className="flex">
            <div className="sticky z-40 top-0 h-screen">
              <SidebarDemo />
            </div>
            <div className="flex-1 flex flex-col">
              <div className="sticky top-0 z-30 bg-background">
                <Navbar />
              </div>
              <main className="flex-1 p-4 z-30">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
