import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import SidebarDemo from "@/components/sidebar";
import { Navbar } from "@/components/navbar/navbar";

export const metadata: Metadata = {
  title: "Bem vindo ao Agras",
  description: "Generated by create next app",
};


export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <div className="flex">
        <div className="sticky z-40 top-0 h-screen">
          <SidebarDemo />
        </div>
        <div className="flex-1 flex flex-col">
          <div className="sticky top-0 z-30">
            <Navbar />
          </div>
          <main className="flex-1 p-4 z-30">{children}</main>
        </div>
      </div>
    </SidebarProvider>
  );
}
