import type { Metadata } from "next";
import {
    SidebarInset,
    SidebarProvider,
    SidebarTrigger,
} from "@/components/ui/sidebar";
import { Navbar } from "@/components/navbar/navbar";
import { Separator } from "@/components/ui/separator";
import { AppSidebar } from "@/components/sidebarnova";

export const metadata: Metadata = {
    title: "Bem vindo ao Agras",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <SidebarProvider>
            <AppSidebar />

            <SidebarInset>
                <Navbar />
                <Separator
                    orientation="horizontal"
                    className="bg-[#CECECE] w-full relative mt-0.5"
                />
                <div className="p-4">{children}</div>
            </SidebarInset>
        </SidebarProvider>
    );
}
